// <auto-generated />
namespace qlts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init3332817 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init3332817));
        
        string IMigrationMetadata.Id
        {
            get { return "202304250844512_init3332817"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
